### ISSUE TITLE
Unlock Hover doesn't work for layers outside an artboard?

### ISSUE THREAD

**Issue by bomberstudios** [truthlabs/sketch-unlock-all-layers#1]
Tried the plugin, and apparently it's not working for shapes that are not contained inside an artboard.

**Comment by eklimcz** [comment]
We're working on adding support for this. Should have another release in the next couple days.

**Comment by sconstantinides** [comment]
Should be working without artboards now. Let me know if you find any issues.

**Comment by bomberstudios** [comment]
Works like a charm, thank you!
