### ISSUE TITLE
Unlock Hover not working in 3.4 beta

### ISSUE THREAD

**Issue by bomberstudios** [truthlabs/sketch-unlock-all-layers#2]
`mouseInScreenCoordinatesInGroup` has been removed so the plugin no longer works in 3.4

I'll send you a pull request that fixes this in a minute : )

**Comment by bomberstudios** [comment]
Please note that the pull request does not fix #1, since that requires a change in the plugin's logic!

**Comment by bomberstudios** [comment]
Also: the fix is backwards compatible (i.e: works in 3.3.3)

**Comment by sconstantinides** [comment]
Great catch, thanks! Do you have link to the 3.4 docs?

**Comment by bomberstudios** [comment]
Well, that thing wasn't exactly documented : )

I'm working on updated docs at the moment (sneak peek: http://developer.sketchapp.com) so I'll just go ahead and document `MSEventHandler` for you : )

**Comment by bomberstudios** [comment]
Check http://developer.sketchapp.com/docs/MSEventHandler/

**Comment by sconstantinides** [comment]
This is super helpful. Cheers!
