### ISSUE TITLE
Support Sketch 45 plugin update system

### ISSUE THREAD

**Issue by bomberstudios** [truthlabs/sketch-unlock-all-layers#6]
Hi there!

This is a quick note to remind you that Sketch 45 will include a plugin update system.

It would be awesome if you could add support to it (it's really easy!) before Sketch 45 comes out. Ideally, you should release an update for your plugin while we're still in Sketch 44, so your users will have a nice & easy experience when 45 is released.

For more details, please check http://sketchplugins.com/d/229-updating-plugins and http://developer.sketchapp.com/introduction/updating-plugins/

Thanks in advance!

**Comment by sconstantinides** [comment]
@bomberstudios Do we need to specify sparkle:dsaSignature for enclosures?

**Comment by bomberstudios** [comment]
Not at the moment, we're keeping it as simple as possible by now : )

**Comment by sconstantinides** [comment]
Thanks for the info.

I've gotten the update button to appear in Sketch Beta but it doesn't do anything. Does the appcast look correct? https://github.com/truthlabs/sketch-unlock-all-layers/blob/master/appcast.xml

**Comment by bomberstudios** [comment]
The appcast looks good, but you need to make sure the ZIP you're downloading contains a higher version than the one you're updating (in your case, you'd be updating v2.2 with v2.2, as far as I can tell)

**Comment by sconstantinides** [comment]
Not sure I follow. This is what I'm seeing...

<img width="448" alt="screen shot 2017-06-06 at 11 27 30 am" src="https://user-images.githubusercontent.com/2643701/26840267-316a5b3e-4aab-11e7-87c8-0f366d0459e0.png">

**Comment by bomberstudios** [comment]
Sorry, that was a mistake on my side 🤦‍♂️ 

You probably want to start using GitHub releases, to make sure each enclosure points to a unique ZIP file (right now, both 2.1 and 2.2 point to the same thing : )

**Comment by sconstantinides** [comment]
Oh, that makes sense. I've split them into releases now (and updated the appcast) but clicking the update button still doesn't do anything...

**Comment by bomberstudios** [comment]
Try deleting this folder `~/Library/Application Support/com.bohemiancoding.sketch3/PluginsWarehouse` and relaunching Sketch : )

**Comment by sconstantinides** [comment]
Beautiful! Thanks!

**Comment by bomberstudios** [comment]
🎉
